[Common]
Login=
Password=
Server=
KeepPrivate=

[StartUp]
Expert=
ExpertParameters=
Symbol=
Period=

[Tester]
;aca se pueden rutas relativas a la carpeta "experts del path de la instancia id"
Expert=EaStudio\
;aca a investigar donde se deberia guardar los sets, para que se puedan usarse.
ExpertParameters=
Symbol=EURUSD
Period=M15
Model=0
Spread=0
FromDate=2025.01.01
ToDate=2025.12.31
Optimization=0
ForwardMode=0
Visual=0
;Aqui se pueden rutas relativas al instancia id
Report=MyExpert.htm 
ReplaceReport=1
ShutdownTerminal=1
Port=3000
