#property copyright "Generated by Codex"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>

CTrade trade;

input int    FastPeriod   = 20;
input int    SlowPeriod   = 50;
input int    TrendPeriod  = 200;
input int    AtrPeriod    = 14;
input double RiskPerTrade = 1.0;   // percent of balance
input double AtrSLMult    = 2.0;
input double AtrTPMult    = 4.0;

double atr[], emaFast[], emaSlow[], emaTrend[];
int    handleATR, handleFast, handleSlow, handleTrend;

int OnInit()
  {
   handleATR   = iATR(_Symbol, _Period, AtrPeriod);
   handleFast  = iMA(_Symbol, _Period, FastPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handleSlow  = iMA(_Symbol, _Period, SlowPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handleTrend = iMA(_Symbol, _Period, TrendPeriod, 0, MODE_EMA, PRICE_CLOSE);

   if(handleATR==INVALID_HANDLE || handleFast==INVALID_HANDLE ||
      handleSlow==INVALID_HANDLE || handleTrend==INVALID_HANDLE)
      return(INIT_FAILED);

   ArraySetAsSeries(atr,true);
   ArraySetAsSeries(emaFast,true);
   ArraySetAsSeries(emaSlow,true);
   ArraySetAsSeries(emaTrend,true);
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   if(handleATR!=INVALID_HANDLE)   IndicatorRelease(handleATR);
   if(handleFast!=INVALID_HANDLE)  IndicatorRelease(handleFast);
   if(handleSlow!=INVALID_HANDLE)  IndicatorRelease(handleSlow);
   if(handleTrend!=INVALID_HANDLE) IndicatorRelease(handleTrend);
  }

void OnTick()
  {
   if(CopyBuffer(handleATR,0,0,3,atr)<3 ||
      CopyBuffer(handleFast,0,0,3,emaFast)<3 ||
      CopyBuffer(handleSlow,0,0,3,emaSlow)<3 ||
      CopyBuffer(handleTrend,0,0,3,emaTrend)<3)
      return;

   double atrVal      = atr[0];
   double fastCurr    = emaFast[0], fastPrev = emaFast[1];
   double slowCurr    = emaSlow[0], slowPrev = emaSlow[1];
   double trendCurr   = emaTrend[0];
   double price       = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   // Maintain single position per symbol
   int total = PositionsTotal();
   int dir=0;
   for(int i=0;i<total;i++)
     {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL)==_Symbol)
        {
         dir = (PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY) ? 1 : -1;
         ManageTrailing(ticket, dir, atrVal);
         return;
        }
     }

   // Cross detections
   bool bullCross = fastPrev <= slowPrev && fastCurr > slowCurr && price > trendCurr;
   bool bearCross = fastPrev >= slowPrev && fastCurr < slowCurr && price < trendCurr;

   if(!bullCross && !bearCross) return;

   double slDist = atrVal * AtrSLMult;
   double tpDist = atrVal * AtrTPMult;
   double lot    = CalculateLot(slDist);
   if(lot<=0) return;

   if(bullCross)
     {
      double sl = price - slDist;
      double tp = price + tpDist;
      trade.Buy(lot, _Symbol, price, sl, tp, "EA_Buenisimo");
     }
   else if(bearCross)
     {
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double sl = ask + slDist;
      double tp = ask - tpDist;
      trade.Sell(lot, _Symbol, ask, sl, tp, "EA_Buenisimo");
     }
  }

double CalculateLot(double slDistPoints)
  {
   if(slDistPoints<=0) return(0);

   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double contract  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE);
   double balance   = AccountInfoDouble(ACCOUNT_BALANCE);

   double riskMoney = balance * (RiskPerTrade/100.0);
   double moneyPerLot = slDistPoints * (tickValue/tickSize);
   double lot = riskMoney / moneyPerLot;

   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double min  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double max  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);

   lot = MathFloor(lot/step)*step;
   lot = MathMax(min, MathMin(max, lot));
   return(lot);
  }

void ManageTrailing(ulong ticket, int dir, double atrVal)
  {
   if(!PositionSelectByTicket(ticket)) return;

   double price = (dir>0) ? SymbolInfoDouble(_Symbol, SYMBOL_BID)
                          : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double sl    = PositionGetDouble(POSITION_SL);
   double trail = atrVal * AtrSLMult;

   if(dir>0)
     {
      double newSL = price - trail;
      if(newSL > sl)
         trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
     }
   else if(dir<0)
     {
      double newSL = price + trail;
      if(sl==0 || newSL < sl)
         trade.PositionModify(ticket, newSL, PositionGetDouble(POSITION_TP));
     }
  }
