;configReal()

KeepPrivate=1
Spread=0
UseDate=1
ToDate=2026.03.01

StartUp=False

Currency=
Company=
LicenseFile=

_6años=2190
_5años=1825
_3años=1095
_2años=730
_1año=365
_6meses=182

posicion1=single_test,"Backtest sin optimización (6M o 1A)",_6meses,_1año
posicion2=genetica,"Optimización genética",_1año,preset
posicion3=single_full,"Backtest largo",_1año,_3años,_6años
posicion4=genetica_fw50,"Genética + forward 50/50",_1año,preset
posicion5=all_full,"Backtest completo",_1año,_5años,preset