[Common]
Login=NUMERO-DE-CUENTA
Password=CONTRASEÑA
Server=SERVIDOR-DE-BROKER
KeepPrivate=1

[StartUp]
Expert=
ExpertParameters=
Symbol=
Period=

[Tester]
;aca se pueden rutas relativas a la carpeta "experts del path de la instancia id"
Expert=EaStudio\example.ex5
ExpertParameters=
Symbol=EURUSD
Period=M15
Model=0
Spread=0
FromDate=2025.01.01
ToDate=2025.12.31
Optimization=0
Visual=0
;Aqui se pueden rutas relativas al instancia id
Report=\reports\MyExpert.htm
ReplaceReport=1
ShutdownTerminal=1
Port=3000
