;configReal()

Deposit=50
Currency=USD
Leverage=1:500



KeepPrivate=1
Spread=0
UseDate=1
ToDate=2026.03.01

StartUp=False

DefaultSymbol=EURUSD

Company=
LicenseFile=

_10años=3650
_9años=3285
_8años=2920
_7años=2555
_6años=2190
_5años=1825
_4años=1460
_3años=1095
_2años=730
_1año=365
_6meses=182


posicion1=single_test,"Backtest para validar logica temprana(sin opt)",_1año
posicion2=visual_debug,"Backtest single_test visual",_1año
posicion3=single_logic,"Backtest para validar resistencia de logica(sin opt)",_10años
posicion4=genetica70_fw30,"Genética 70% + forward 30%(requiere .set fresco)",_3años,_10años,preset
posicion5=single_full,"Backtest para validar parametros nuevos(con .set opt)",_3años,_10años,preset
posicion6=single_all_symbols,"Backtestes para validar polivalencia multisimbolo(con .set opt)",_10años,preset