//+------------------------------------------------------------------+
//|                                                   ea_superior.mq5|
//|           Auto-generated by Codex                              |
//+------------------------------------------------------------------+
#property copyright ""
#property link      ""
#property version   "1.01"
#property strict

#include <Trade/Trade.mqh>

input string   InpSymbol          = "";          // Símbolo a operar (vacío = símbolo del gráfico)
input ENUM_TIMEFRAMES InpTimeframe= PERIOD_H1;    // Timeframe operativo
input double   InpRiskPercent     = 1.0;          // % balance a arriesgar por trade
input double   InpSL_ATR_mult     = 2.5;          // Multiplicador ATR para StopLoss
input double   InpTP_ATR_mult     = 4.0;          // Multiplicador ATR para TakeProfit
input bool     InpUseTrailing     = true;         // Activar trailing stop
input double   InpTrail_ATR_mult  = 1.5;          // Multiplicador ATR para trailing
input int      InpRSI_Period      = 14;           // Periodo RSI
input int      InpRSI_BuyLevel    = 35;           // Nivel inferior RSI para compras
input int      InpRSI_SellLevel   = 65;           // Nivel superior RSI para ventas
input int      InpEMASlow         = 200;          // EMA lenta (tendencia)
input int      InpEMAFast         = 20;           // EMA rápida (pullback)
input double   InpMaxSpreadPoints = 30;           // Spread máximo permitido (puntos del símbolo)
input bool     InpUseTradingWindow= false;        // Usar ventana horaria
input int      InpTradeHourStart  = 0;            // Hora inicio [0,23]
input int      InpTradeHourEnd    = 23;           // Hora fin (excluyente)
input ulong    InpMagic           = 20260304;     // Magic number

CTrade trade;
string   g_symbol;
int      hEmaSlow = INVALID_HANDLE;
int      hEmaFast = INVALID_HANDLE;
int      hRsi     = INVALID_HANDLE;
int      hAtr     = INVALID_HANDLE;
datetime g_lastBar = 0;

//+------------------------------------------------------------------+
//| Helpers                                                          |
//+------------------------------------------------------------------+
bool SetupSymbol()
{
   g_symbol = StringTrim(InpSymbol);
   if(g_symbol == "") g_symbol = Symbol();
   g_symbol = StringToUpper(g_symbol);

   if(!SymbolInfoInteger(g_symbol, SYMBOL_SELECT))
   {
      PrintFormat("[EA] No se pudo seleccionar símbolo %s", g_symbol);
      return false;
   }

   hEmaSlow = iMA(g_symbol, InpTimeframe, InpEMASlow, 0, MODE_EMA, PRICE_CLOSE);
   hEmaFast = iMA(g_symbol, InpTimeframe, InpEMAFast, 0, MODE_EMA, PRICE_CLOSE);
   hRsi     = iRSI(g_symbol, InpTimeframe, InpRSI_Period, PRICE_CLOSE);
   hAtr     = iATR(g_symbol, InpTimeframe, 14);

   if(hEmaSlow==INVALID_HANDLE || hEmaFast==INVALID_HANDLE || hRsi==INVALID_HANDLE || hAtr==INVALID_HANDLE)
   {
      Print("[EA] Error creando indicadores");
      return false;
   }

   datetime t[1];
   if(CopyTime(g_symbol, InpTimeframe, 0, 1, t)==1)
      g_lastBar = t[0];
   else
      g_lastBar = 0;

   return true;
}

bool SpreadOK()
{
   double spreadPoints = (SymbolInfoDouble(g_symbol, SYMBOL_ASK) - SymbolInfoDouble(g_symbol, SYMBOL_BID)) / SymbolInfoDouble(g_symbol, SYMBOL_POINT);
   return (spreadPoints <= InpMaxSpreadPoints);
}

bool InTradingWindow()
{
   if(!InpUseTradingWindow) return true;
   datetime serverTime = TimeTradeServer();
   int hour = TimeHour(serverTime);
   if(InpTradeHourStart <= InpTradeHourEnd)
      return (hour >= InpTradeHourStart && hour < InpTradeHourEnd);
   return (hour >= InpTradeHourStart || hour < InpTradeHourEnd);
}

bool PositionExists(bool isLong)
{
   for(int i=0;i<PositionsTotal();i++)
   {
      if(!PositionSelectByIndex(i)) continue;
      if(PositionGetString(POSITION_SYMBOL)!=g_symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC)!=(long)InpMagic) continue;
      long type = PositionGetInteger(POSITION_TYPE);
      if((isLong && type==POSITION_TYPE_BUY) || (!isLong && type==POSITION_TYPE_SELL))
         return true;
   }
   return false;
}

bool CalcLotSize(double slPriceDistance, double riskPercent, double &volume)
{
   double balance   = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskMoney = balance * riskPercent / 100.0;

   double tickVal   = SymbolInfoDouble(g_symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(g_symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickVal<=0 || tickSize<=0 || slPriceDistance<=0) return false;

   double slTicks = slPriceDistance / tickSize;
   double costPerLot = slTicks * tickVal;
   if(costPerLot <= 0) return false;

   double rawVol = riskMoney / costPerLot;

   double lotStep = SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_STEP);
   double lotMin  = SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_MIN);
   double lotMax  = SymbolInfoDouble(g_symbol, SYMBOL_VOLUME_MAX);

   volume = MathFloor(rawVol / lotStep) * lotStep;
   if(volume < lotMin) volume = lotMin;
   if(volume > lotMax) volume = lotMax;

   return (volume >= lotMin && volume <= lotMax);
}

void ReleaseIndicators()
{
   if(hEmaSlow!=INVALID_HANDLE) IndicatorRelease(hEmaSlow);
   if(hEmaFast!=INVALID_HANDLE) IndicatorRelease(hEmaFast);
   if(hRsi!=INVALID_HANDLE)     IndicatorRelease(hRsi);
   if(hAtr!=INVALID_HANDLE)     IndicatorRelease(hAtr);
}

void ManageTrailing()
{
   if(!InpUseTrailing) return;
   if(hAtr==INVALID_HANDLE) return;

   double atrBuf[1];
   if(CopyBuffer(hAtr,0,0,1,atrBuf)!=1) return;
   double atr = atrBuf[0];
   if(atr<=0) return;

   for(int i=0;i<PositionsTotal();i++)
   {
      if(!PositionSelectByIndex(i)) continue;
      if(PositionGetString(POSITION_SYMBOL)!=g_symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC)!=(long)InpMagic) continue;

      long   type = PositionGetInteger(POSITION_TYPE);
      double sl   = PositionGetDouble(POSITION_SL);
      double newSL;
      if(type==POSITION_TYPE_BUY)
      {
         newSL = SymbolInfoDouble(g_symbol, SYMBOL_BID) - atr*InpTrail_ATR_mult;
         if(sl==0 || newSL > sl)
            trade.PositionModify(g_symbol, newSL, PositionGetDouble(POSITION_TP));
      }
      else if(type==POSITION_TYPE_SELL)
      {
         newSL = SymbolInfoDouble(g_symbol, SYMBOL_ASK) + atr*InpTrail_ATR_mult;
         if(sl==0 || newSL < sl)
            trade.PositionModify(g_symbol, newSL, PositionGetDouble(POSITION_TP));
      }
   }
}

//+------------------------------------------------------------------+
//| Setup                                                            |
//+------------------------------------------------------------------+
int OnInit()
{
   if(!SetupSymbol()) return INIT_FAILED;
   trade.SetExpertMagicNumber((int)InpMagic);
   EventSetTimer(15); // por si no hay ticks
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   ReleaseIndicators();
   EventKillTimer();
}

void OnTick()
{
   ProcessSignals();
   ManageTrailing();
}

void OnTimer()
{
   ProcessSignals();
   ManageTrailing();
}

//+------------------------------------------------------------------+
void ProcessSignals()
{
   if(!InTradingWindow()) return;

   datetime t[2];
   if(CopyTime(g_symbol, InpTimeframe, 0, 2, t) < 2) return;
   if(t[0] == g_lastBar) return;
   g_lastBar = t[0];

   if(!SpreadOK())
   {
      PrintFormat("[EA] Spread alto en %s, no opero esta barra", g_symbol);
      return;
   }

   double emaSlow[2], emaFast[2], rsi[2], atr[1];
   if(CopyBuffer(hEmaSlow,0,0,2,emaSlow)<2) return;
   if(CopyBuffer(hEmaFast,0,0,2,emaFast)<2) return;
   if(CopyBuffer(hRsi,0,0,2,rsi)<2) return;
   if(CopyBuffer(hAtr,0,0,1,atr)<1) return;
   double closePrice = iClose(g_symbol, InpTimeframe, 0);

   double atrVal = atr[0];
   if(atrVal<=0) return;

   bool longBias  = closePrice > emaSlow[0] && emaFast[0] > emaSlow[0];
   bool shortBias = closePrice < emaSlow[0] && emaFast[0] < emaSlow[0];

   bool longSignal  = longBias  && (rsi[1] < InpRSI_BuyLevel)  && (rsi[0] > rsi[1]) && closePrice >= emaFast[0];
   bool shortSignal = shortBias && (rsi[1] > InpRSI_SellLevel) && (rsi[0] < rsi[1]) && closePrice <= emaFast[0];

   if(longSignal && !PositionExists(true))
      OpenPosition(ORDER_TYPE_BUY, closePrice, atrVal);
   if(shortSignal && !PositionExists(false))
      OpenPosition(ORDER_TYPE_SELL, closePrice, atrVal);
}

//+------------------------------------------------------------------+
void OpenPosition(ENUM_ORDER_TYPE type, double price, double atr)
{
   double slDist = atr * InpSL_ATR_mult;
   double tpDist = atr * InpTP_ATR_mult;

   double sl=0, tp=0;
   if(type == ORDER_TYPE_BUY)
   {
      sl = price - slDist;
      tp = price + tpDist;
   }
   else if(type == ORDER_TYPE_SELL)
   {
      sl = price + slDist;
      tp = price - tpDist;
   }

   double volume;
   if(!CalcLotSize(slDist, InpRiskPercent, volume))
   {
      PrintFormat("[EA] No se pudo calcular lote para %s", g_symbol);
      return;
   }

   trade.SetExpertMagicNumber((int)InpMagic);
   trade.SetDeviationInPoints(10);

   bool result=false;
   double ask = SymbolInfoDouble(g_symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(g_symbol, SYMBOL_BID);

   if(type == ORDER_TYPE_BUY)
      result = trade.Buy(volume, g_symbol, ask, sl, tp, "EA Superior buy");
   else
      result = trade.Sell(volume, g_symbol, bid, sl, tp, "EA Superior sell");

   if(!result)
      PrintFormat("[EA] Falló orden en %s. Error %d", g_symbol, GetLastError());
}

//+------------------------------------------------------------------+
//| OnTester: calcula métricas y devuelve fitness                    |
//+------------------------------------------------------------------+
double OnTester()
{
   double trades      = TesterStatistics(STAT_TRADES);
   double wins        = TesterStatistics(STAT_PROFITTRADES);
   double losses      = TesterStatistics(STAT_LOSSTRADES);
   double grossProfit = TesterStatistics(STAT_GROSSPROFIT);
   double grossLoss   = TesterStatistics(STAT_GROSSLOSS);
   double netProfit   = TesterStatistics(STAT_PROFIT);
   double pf          = TesterStatistics(STAT_PROFITFACTOR);
   double maxDD       = TesterStatistics(STAT_RELATIVEDRAW); // %
   double recov       = TesterStatistics(STAT_RECOVERYFACTOR);
   double avgTrade    = (trades>0) ? netProfit / trades : 0;
   double winrate     = (trades>0) ? wins / trades : 0;
   double avgWin      = (wins>0) ? grossProfit / wins : 0;
   double avgLoss     = (losses>0) ? MathAbs(grossLoss) / losses : 0;
   double payoff      = (avgLoss>0) ? avgWin / avgLoss : 0;
   double sharpe      = TesterStatistics(STAT_SHARPE_RATIO);
   double avgHold     = 0; // placeholder

   double fitness = (pf * winrate) / (1.0 + maxDD/100.0);

   PrintFormat("[OnTester] Trades=%0.0f Winrate=%.2f%% PF=%.2f MaxDD=%.2f%% Recov=%.2f Payoff=%.2f AvgTrade=%.2f Sharpe=%.2f AvgHold(s)=%.0f Fitness=%.4f",
               trades, winrate*100.0, pf, maxDD, recov, payoff, avgTrade, sharpe, avgHold, fitness);

   Comment(StringFormat("PF %.2f | Winrate %.1f%% | DD %.2f%% | Payoff %.2f | Trades %.0f | Fitness %.4f",
            pf, winrate*100.0, maxDD, payoff, trades, fitness));

   return fitness;
}
//+------------------------------------------------------------------+
